// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1huYHPshm2C0Uzm1eSPpGvTsdSAiQhmw',
    appId: '1:389809615687:web:666ab20c7c0900b99f9262',
    messagingSenderId: '389809615687',
    projectId: 'runner2026scout',
    authDomain: 'runner2026scout.firebaseapp.com',
    storageBucket: 'runner2026scout.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmn4aqHYfnUY4Q4ml27kM7pSooayK9HWk',
    appId: '1:389809615687:android:b5c757919616fe1c9f9262',
    messagingSenderId: '389809615687',
    projectId: 'runner2026scout',
    storageBucket: 'runner2026scout.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsHVbSuhQX5GUUXLCfxU18Mz5lmB6p7X0',
    appId: '1:389809615687:ios:34effcdd34d663bb9f9262',
    messagingSenderId: '389809615687',
    projectId: 'runner2026scout',
    storageBucket: 'runner2026scout.firebasestorage.app',
    iosBundleId: 'com.example.runnerScoutApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsHVbSuhQX5GUUXLCfxU18Mz5lmB6p7X0',
    appId: '1:389809615687:ios:34effcdd34d663bb9f9262',
    messagingSenderId: '389809615687',
    projectId: 'runner2026scout',
    storageBucket: 'runner2026scout.firebasestorage.app',
    iosBundleId: 'com.example.runnerScoutApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1huYHPshm2C0Uzm1eSPpGvTsdSAiQhmw',
    appId: '1:389809615687:web:e2ef457938a6024c9f9262',
    messagingSenderId: '389809615687',
    projectId: 'runner2026scout',
    authDomain: 'runner2026scout.firebaseapp.com',
    storageBucket: 'runner2026scout.firebasestorage.app',
  );
}
